# Generated by Django 5.0.2 on 2024-12-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumProfile', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='SeregaPirate/static/ForumProfile/avatar.jpg', null=True, upload_to='SeregaPirate/static/ForumProfile/'),
        ),
    ]
