# Generated by Django 5.0.2 on 2024-12-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumProfile', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='SeregaPirat/static/ForumProfile/avatar.jpg', null=True, upload_to='SeregaPirat/static/ForumProfile/'),
        ),
    ]
